name: Unit Tests
env:
  # increment this when downloads substantially change to avoid the internet
  DOWNLOAD_CACHE_VERSION: '6'
  RUN_PROCESS_REPLAY: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHONPATH: .

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  testwindows:
    name: Windows Tests
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Cache python packages
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Roaming\Python\Python311\site-packages
        key: windows-testing-user3-packages-${{ hashFiles('**/setup.py') }}
    - name: Install Dependencies
      run: pip install --user -e '.[testing]'
    - name: Cache downloads
      uses: actions/cache@v4
      with:
        path: C:\\Users\\runneradmin\\.cache\\tinygrad\\downloads\
        key: downloads-cache-windows-only-${{ env.DOWNLOAD_CACHE_VERSION }}
    - name: Run windows test
      run: python -m pytest test/ --ignore=test/external --ignore=test/models --ignore=test/unit --durations=20
